# Generated by Django 2.2.3 on 2019-07-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
